### ISSUE TITLE
No build-system.jam

### ISSUE THREAD

**Issue by RoverUser** [ui0ppk/roblox-master#3]
When i'm trying to compile Boost, it can't find `build-system.jam` file, i tried to search `build-system.jam` in every subdirectory, but there is no `build-system.jam`, i think the problem is because in .gitignore, at line 417, there is "`*build-*`", and git just skipped build-system.jam during uploading files into this repository, because of similar file names, or is this file auto-generated, and i broke something so this file didn't appeared?
![cmd](https://user-images.githubusercontent.com/78263062/193632208-c03be4b3-ab15-49b2-aa8f-9c84ef140c1c.png)

**Comment by ui0ppk** [comment]
Missing Dependencies...?

**Comment by olavito** [comment]
i'm also getting this issue

**Comment by LukeDevsE** [comment]
that is indeed correct
![image](https://user-images.githubusercontent.com/108841495/211180438-c9dfb8ff-06a7-47f5-87fe-5313ae371ab4.png)
shows up here
but not in the main file

**Comment by LukeDevsE** [comment]
that seems like the issue

**Comment by Derailedzack** [comment]
It might be possible to source this from boost

**Comment by Derailedzack** [comment]
If you want I could fork this and create a pull request

**Comment by Fliatzel** [comment]
> If you want I could fork this and create a pull request or I could attach the build-system.jam

No, Instead download the original libraries and use the normal source, this version is hell in a vs code

https://sourceforge.net/projects/boost/files/boost/1.56.0/boost_1_56_0.zip/download

https://download.qt.io/archive/qt/4.8/4.8.5/qt-everywhere-opensource-src-4.8.5.zip

**Comment by Fliatzel** [comment]
also this post probably needs to be closed as this fixes the issue
