### ISSUE TITLE
Very important Issue

### ISSUE THREAD

**Issue by notalphadev** [ui0ppk/roblox-master#4]
Issue raised by Arseny Kapoulkine: <https://twitter.com/zeuxcg/status/1054886580496740352>.

Arseny Kapoulkine is under NDA and is in no way permitted to share proprietary file names and portions of source code on any non ROBLOX intranet services.

Sorry, @ui0ppk.

**Comment by ui0ppk** [comment]
my balls itch

**Comment by ui0ppk** [comment]
> Arseny Kapoulkine is under NDA and is in no way permitted to share proprietary file names and portions of source code on any non ROBLOX intranet services.

but i didnt sign any NDA, so wdfym.
